AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-pipeline

  Sample SAM Template for sam-pipeline

Parameters:
  EnvName:
    Type: String
    Default: "stage"

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        ENV_NAME: !Ref EnvName

Resources:
  HelloWorldFunctionEndpointAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 60
  HelloWorldFunctionEndpoint:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api
      Cors:
        AllowMethods: "'OPTIONS,POST'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      AccessLogSetting:
        DestinationArn: !GetAtt HelloWorldFunctionEndpointAccessLogGroup.Arn
        Format: '{"requestTime":"$context.requestTime","requestId":"$context.requestId","httpMethod":"$context.httpMethod","path":"$context.path","status":$context.status,"responseLatency":$context.responseLatency,"integrationRequestId":"$context.integration.requestId","functionResponseStatus":"$context.integration.status"}'
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      AutoPublishAlias: live
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
            RestApiId: !Ref HelloWorldFunctionEndpoint
  # HelloWorldFunctionVersion:
  #   Type: AWS::Lambda::Version
  #   Properties:
  #     FunctionName: !Ref HelloWorldFunction
  # HelloWorldFunctionAlias:
  #   Type: AWS::Lambda::Alias
  #   Properties:
  #     FunctionName: !Ref HelloWorldFunction
  #     FunctionVersion: !GetAtt HelloWorldFunctionVersion.Version
  #     Name: v1
